# Generated by Django 3.1.1 on 2020-09-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('img_url', models.ImageField(upload_to='media/tshirts/')),
            ],
        ),
        migrations.CreateModel(
            name='TshirtRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tshirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tshirt')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key_points', models.TextField()),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('tshirt_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tshirtroom')),
            ],
        ),
    ]
