# Generated by Django 3.1.1 on 2020-09-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirt',
            name='img_url',
            field=models.ImageField(upload_to='tshirts/'),
        ),
    ]
