# Generated by Django 3.1.1 on 2020-09-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tshirtroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
